package org.asciidoctor.leanpub

import org.asciidoctor.leanpub.internal.LeanpubSpecification
import spock.lang.Issue

class DrawingSpec extends LeanpubSpecification {

    void setup() {
        asciidoctor.requireLibrary('asciidoctor-diagram')
    }

    @Issue('https://github.com/aciidoctor/asciidoctor-leanpub-converter/issues/43')
    def "Inline and block content"() {
        setup:
            File chapter = new File(MANUSCRIPT_DIR,'chapter_1.txt')

        when:
            generateOutput('drawing.adoc', false)

        then:
            chapter.text ==~ /# Ditaa\n\n\!\[Generated by Ditaa\]\(images\/diag-\p{XDigit}{32}\.png\s"Generated by Ditaa"\)\n/
    }

}
