package org.asciidoctor.leanpub

import org.asciidoctor.leanpub.internal.LeanpubSpecification
import spock.lang.Issue

/**
 * Created by schalkc on 15/12/14.
 */
class DrawingSpec extends LeanpubSpecification {

    void setup() {
        asciidoctor.requireLibrary('asciidoctor-diagram')
    }

//    @Issue('https://github.com/ysb33r/asciidoctor-leanpub-converter/issues/41')
    def "Inline and block content"() {
        setup:
            File chapter = new File(manuscriptDir,'chapter_1.txt')

        when:
            generateOutput('drawing.adoc')

        then:
            chapter.text ==~ /# Ditaa\n\n\!\[Generated by Ditaa\]\(images\/diag-\p{XDigit}{32}\.png\s"Generated by Ditaa"\)\n/
    }

}
